In [1]:
import geopandas as gpd
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np

In [14]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [33]:
#rutas (ALEJANDRO - SSD)
manzanas_gpkg_path = r"D:\AFC\SSD\VOCES\DATA\Tratados\NAC\INT_MZN_NAC\Mzn_Tipologías_NAC_ImpEq_BufferB.gpkg"
capa = 'Mzn_Subtipologias_UeEQ_filtrado'

# Cargar el archivo de manzanas
gdf_manzanas = gpd.read_file(manzanas_gpkg_path, layer=capa)

In [41]:
gdf_manzanas_intacto = gdf_manzanas.copy()

# Nuevo procesamiento

## op 1

In [4]:
gdf_manzanas.columns

Index(['CVEGEO', 'POPTOT2010', 'POPTOT2020', 'VIVTOT2010', 'VIVTOT2020',
       'TVIVHAB2010', 'TVIVHAB2020', 'TVIVPAR2010', 'TVIVPAR2020',
       'TVIVPARHAB2010',
       ...
       'CVE_SAL_B', 'CVE_REC_B', 'CVE_SER_B', 'CVE_EQ_B', 'CVE_EDU_C',
       'CVE_SAL_C', 'CVE_REC_C', 'CVE_SER_C', 'CVE_EQ_C', 'geometry'],
      dtype='object', length=115)

In [6]:
for col in ['IMP_EDU_C', 'IMP_SAL_C', 'IMP_REC_C', 'IMP_SER_C']:
    gdf_manzanas[col + '_pct'] = gdf_manzanas[col].rank(pct=True)

In [8]:
gdf_manzanas['ICE'] = (
    gdf_manzanas['IMP_EDU_C_pct'] +
    gdf_manzanas['IMP_SAL_C_pct'] +
    gdf_manzanas['IMP_REC_C_pct'] +
    gdf_manzanas['IMP_SER_C_pct']
) / 4

In [9]:
gdf_manzanas['ICE_cat'] = pd.qcut(gdf_manzanas['ICE'], 6, labels=['Muy baja','Baja','Media','Alta','Muy alta', 'Altísima'])

In [11]:
tabla_revision = (
    gdf_manzanas.groupby(['ICE_cat'])
      .size()
      .reset_index(name='n')
      .sort_values('ICE_cat')
)
tabla_revision.loc['Total'] = tabla_revision.sum(numeric_only=True)
tabla_revision

C:\Users\Alejandro\AppData\Local\Temp\ipykernel_9900\2154407781.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  gdf_manzanas.groupby(['ICE_cat'])
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_9900\2154407781.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  tabla_revision.loc['Total'] = tabla_revision.sum(numeric_only=True)

        ICE_cat         n
0      Muy baja  156385.0
1          Baja  156383.0
2         Media  156374.0
3          Alta  156386.0
4      Muy alta  156375.0
5      Altísima  156381.0
Total       NaN  938284.0

## op 2

In [12]:
T = {
    'EDU': 1140,
    'SAL': 13.5,
    'REC': 185.5,
    'SER': 18.5
}

gdf_manzanas['RC_EDU'] = gdf_manzanas['IMP_EDU_C'] / T['EDU']
gdf_manzanas['RC_SAL'] = gdf_manzanas['IMP_SAL_C'] / T['SAL']
gdf_manzanas['RC_REC'] = gdf_manzanas['IMP_REC_C'] / T['REC']
gdf_manzanas['RC_SER'] = gdf_manzanas['IMP_SER_C'] / T['SER']

In [14]:
gdf_manzanas['ICE_norm'] = (
    gdf_manzanas['RC_EDU'] +
    gdf_manzanas['RC_SAL'] +
    gdf_manzanas['RC_REC'] +
    gdf_manzanas['RC_SER']
) / 4

In [18]:
# Mostrar estadísticas descriptivas sin notación exponencial
stats = gdf_manzanas['ICE_norm'].describe()
print(stats)

count    938284.000000
mean          5.351988
std           4.001786
min           0.000000
25%           2.282142
50%           4.355480
75%           7.459351
max          23.245143
Name: ICE_norm, dtype: float64

In [15]:
def clasificar_6(x):
    if x < 0.5:
        return 'F'
    elif x < 0.75:
        return 'E'
    elif x < 1:
        return 'D'
    elif x < 1.5:
        return 'C'
    elif x < 2.5:
        return 'B'
    else:
        return 'A'

gdf_manzanas['ICE_cat'] = gdf_manzanas['ICE_norm'].apply(clasificar_6)

In [17]:
gdf_manzanas['ICE_cat'].value_counts(normalize=True)

ICE_cat
A    0.722267
B    0.130323
C    0.064597
D    0.035244
E    0.027543
F    0.020026
Name: proportion, dtype: float64

## op 3

In [50]:
T = {
    'EDU': gdf_manzanas['IMP_EDU_C'].quantile(0.5),
    'SAL': gdf_manzanas['IMP_SAL_C'].quantile(0.5),
    'REC': gdf_manzanas['IMP_REC_C'].quantile(0.5),
    'SER': gdf_manzanas['IMP_SER_C'].quantile(0.5)
}

In [51]:
gdf_manzanas['IMP_EQ_nueva'] = (
    gdf_manzanas['IMP_EDU_C']/T['EDU'] +
    gdf_manzanas['IMP_SAL_C']/T['SAL'] +
    gdf_manzanas['IMP_REC_C']/T['REC'] +
    gdf_manzanas['IMP_SER_C']/T['SER']
) / 4

In [52]:
# Mostrar estadísticas descriptivas sin notación exponencial
stats = gdf_manzanas['IMP_EQ_nueva'].describe()
print(stats)

count    938284.000000
mean          2.157746
std           1.996988
min           0.000000
25%           0.803879
50%           1.469880
75%           2.968614
max          14.363233
Name: IMP_EQ_nueva, dtype: float64

In [55]:
def clasificar_6(x):
    if x < 0.6:
        return 'F'
    elif x < 0.85:
        return 'E'
    elif x < 1:
        return 'D'
    elif x < 1.6:
        return 'C'
    elif x < 2.8:
        return 'B'
    else:
        return 'A'

gdf_manzanas['CVE_EQ_C_nueva'] = gdf_manzanas['IMP_EQ_nueva'].apply(clasificar_6)

In [56]:
gdf_manzanas['CVE_EQ_C_nueva'].value_counts(normalize=True)

CVE_EQ_C_nueva
A    0.268827
C    0.202672
B    0.197285
F    0.174093
E    0.094085
D    0.063038
Name: proportion, dtype: float64

### revisión

In [30]:
gdf_manzanas.groupby('CVE_MET')['ICE_norm'].mean()
gdf_manzanas.groupby('CVE_MET')['ICE_norm'].median()
gdf_manzanas.groupby('CVE_MET')['ICE_cat'].value_counts(normalize=True)

CVE_MET  ICE_cat
01.1.01  A          0.860695
         C          0.042405
         D          0.026567
         B          0.025886
         F          0.025290
         E          0.019159
02.1.01  B          0.361841
         C          0.218607
         F          0.200629
         E          0.103462
         D          0.069591
         A          0.045869
02.2.02  F          0.957089
         E          0.030535
         C          0.009685
         D          0.002690
02.2.03  C          0.515580
         F          0.180968
         B          0.115351
         D          0.096440
         E          0.091662
03.2.01  F          0.298453
         C          0.288893
         E          0.206501
         D          0.118025
         B          0.088128
03.2.02  F          0.607504
         C          0.205410
         E          0.103490
         D          0.075567
         B          0.008028
04.2.01  C          0.297948
         E          0.289740
         D          0.199179
         F          0.187141
         B          0.025992
05.1.01  C          0.383545
         E          0.148553
         F          0.147791
         B          0.134434
         D          0.132199
         A          0.053479
05.1.02  F          0.639126
         E          0.255040
         D          0.054979
         C          0.045357
         B          0.005498
05.1.03  C          0.290207
         B          0.277179
         F          0.211590
         E          0.149820
         D          0.071204
05.1.04  B          0.355506
         C          0.304621
         F          0.124147
         E          0.104452
         D          0.065676
         A          0.045597
05.3.05  F          0.449422
         E          0.249422
         C          0.197977
         D          0.101156
         B          0.002023
06.1.01  C          0.324306
         E          0.249702
         F          0.215636
         D          0.133367
         B          0.076989
06.3.02  C          0.297087
         E          0.252359
         F          0.229791
         D          0.150595
         B          0.070168
07.1.01  F          0.448953
         C          0.240017
         E          0.157134
         B          0.096913
         D          0.056983
07.1.02  F          0.647069
         B          0.133945
         C          0.098526
         E          0.078839
         D          0.038835
         A          0.002787
08.1.01  F          0.336989
         B          0.299297
         C          0.197136
         E          0.078684
         A          0.046316
         D          0.041578
08.1.02  F          0.649351
         E          0.226494
         C          0.065195
         D          0.058961
08.2.03  F          0.388399
         C          0.164337
         E          0.147880
         B          0.143920
         D          0.112484
         A          0.042980
08.3.04  E          0.418146
         C          0.292308
         D          0.151874
         F          0.137673
09.1.01  A          0.568056
         B          0.273538
         C          0.089006
         F          0.042119
         E          0.015325
         D          0.011956
10.2.01  C          0.399017
         E          0.268240
         F          0.168437
         D          0.134808
         B          0.029499
11.1.01  F          0.449726
         E          0.358761
         D          0.102912
         C          0.075162
         B          0.013440
11.1.02  C          0.366563
         B          0.225545
         F          0.161683
         E          0.144169
         D          0.094404
         A          0.007636
11.2.03  F          0.586083
         E          0.250359
         C          0.080703
         D          0.076758
         B          0.006098
11.2.04  F          0.957224
         E          0.032481
         C          0.009940
         D          0.000355
11.3.05  F          0.991736
         E          0.006612
         D          0.001653
11.3.06  F          0.733115
         E          0.182462
         C          0.047386
         D          0.037037
12.1.01  B          0.355897
         C          0.281228
         F          0.204292
         E          0.110084
         D          0.048500
12.2.02  B          0.460438
         C          0.281376
         A          0.113208
         F          0.081741
         E          0.039197
         D          0.024041
13.1.01  F          0.460282
         B          0.219491
         E          0.121328
         C          0.119109
         D          0.079613
         A          0.000178
13.1.02  F          0.297684
         E          0.286531
         C          0.277667
         D          0.126394
         B          0.011724
13.3.03  F          0.535061
         E          0.361280
         D          0.074695
         C          0.028963
14.1.01  A          0.574679
         B          0.250335
         C          0.104256
         F          0.034605
         E          0.019172
         D          0.016953
14.1.02  C          0.359848
         E          0.273698
         F          0.161626
         B          0.129225
         D          0.072427
         A          0.003177
14.3.03  C          0.581910
         E          0.150438
         F          0.120904
         D          0.120904
         B          0.025842
15.1.01  A          0.554492
         B          0.369681
         C          0.058292
         E          0.007661
         D          0.005745
         F          0.004130
15.3.02  B          0.959845
         C          0.037565
         A          0.002591
15.3.03  A          0.999082
         B          0.000918
16.1.01  F          0.916175
         E          0.058551
         C          0.017270
         D          0.008003
16.1.02  C          0.398899
         B          0.383377
         F          0.126100
         D          0.062084
         E          0.026751
         A          0.002790
16.1.03  E          0.442996
         F          0.354760
         D          0.106731
         C          0.095209
         B          0.000303
16.2.04  F          0.471813
         E          0.323504
         D          0.122940
         C          0.081093
         B          0.000650
16.3.05  F          0.708913
         E          0.207431
         D          0.059722
         C          0.023934
16.3.06  F          0.396192
         C          0.270885
         D          0.209459
         E          0.122850
         B          0.000614
17.1.01  A          0.876323
         B          0.051587
         C          0.041887
         D          0.014550
         E          0.011684
         F          0.003968
17.1.02  A          0.813626
         B          0.156875
         C          0.011365
         F          0.007080
         E          0.006086
         D          0.004968
18.1.01  B          0.546110
         A          0.219591
         C          0.170907
         F          0.034270
         D          0.017061
         E          0.012061
19.1.01  A          0.703227
         B          0.107456
         F          0.066695
         C          0.059911
         E          0.041227
         D          0.021484
20.1.01  A          0.837270
         B          0.099123
         C          0.046520
         D          0.010378
         E          0.005815
         F          0.000895
20.3.02  C          0.431798
         F          0.273251
         E          0.156333
         D          0.100531
         B          0.038087
20.3.03  E          0.388889
         D          0.253535
         C          0.238889
         F          0.114141
         B          0.004545
20.3.04  E          0.343370
         F          0.285466
         D          0.227562
         C          0.143602
21.1.01  C          0.358174
         B          0.260030
         A          0.118739
         E          0.102720
         D          0.102093
         F          0.058244
21.1.02  C          0.463244
         E          0.214763
         B          0.109964
         F          0.107230
         D          0.104800
21.1.03  F          0.294769
         C          0.242460
         B          0.213007
         E          0.170123
         D          0.079642
21.3.04  C          0.648532
         D          0.221071
         E          0.122625
         B          0.006908
         F          0.000864
21.3.05  C          0.846305
         D          0.108374
         E          0.022660
         B          0.020690
         F          0.001970
22.1.01  F          0.363978
         C          0.314641
         D          0.170718
         E          0.141105
         B          0.009558
23.1.01  C          0.457825
         E          0.144291
         D          0.134617
         A          0.095742
         B          0.085978
         F          0.081548
23.2.02  F          0.673023
         E          0.280713
         C          0.026571
         D          0.019694
23.2.03  F          0.445415
         C          0.311681
         E          0.148745
         D          0.091430
         B          0.002729
24.1.01  C          0.360871
         B          0.313824
         E          0.121346
         F          0.121280
         D          0.069878
         A          0.012801
24.3.02  C          0.501307
         B          0.411396
         D          0.051228
         E          0.035546
         F          0.000523
24.3.03  C          0.348551
         F          0.302174
         E          0.239130
         D          0.106522
         B          0.003623
25.2.01  C          0.410159
         E          0.169840
         B          0.152885
         D          0.140312
         F          0.123788
         A          0.003017
25.2.02  F          0.534635
         E          0.283644
         C          0.093836
         D          0.072170
         B          0.015716
25.2.03  C          0.442052
         D          0.260671
         E          0.238125
         F          0.040152
         B          0.018999
26.1.01  F          0.939493
         E          0.045380
         C          0.012061
         D          0.003066
26.2.02  C          0.479495
         B          0.286900
         F          0.105429
         D          0.071891
         E          0.056284
26.2.03  A          0.571743
         B          0.302589
         F          0.083956
         C          0.033035
         D          0.004872
         E          0.003804
26.2.04  C          0.378125
         E          0.280000
         D          0.250000
         F          0.091875
26.3.05  F          0.620435
         E          0.223388
         D          0.112665
         C          0.043512
27.1.01  C          0.285806
         B          0.256267
         F          0.146415
         A          0.140987
         E          0.121986
         D          0.048539
28.1.01  C          0.262944
         E          0.247172
         F          0.245499
         B          0.122033
         D          0.120599
         A          0.001752
28.1.02  C          0.385498
         F          0.235860
         B          0.159699
         E          0.141143
         D          0.077502
         A          0.000298
28.2.03  C          0.614319
         B          0.224141
         D          0.095881
         E          0.052887
         F          0.008455
         A          0.004317
28.2.04  B          0.491350
         C          0.300543
         D          0.084985
         E          0.063139
         A          0.033843
         F          0.026140
28.2.05  C          0.381655
         E          0.182699
         B          0.170768
         D          0.144072
         F          0.120805
29.1.01  A          0.911028
         B          0.072994
         C          0.015979
29.3.02  A          0.856223
         B          0.143777
30.1.01  C          0.412902
         E          0.201953
         D          0.194104
         F          0.160031
         B          0.031011
30.1.02  C          0.378112
         B          0.349739
         D          0.094094
         E          0.093515
         F          0.084540
30.1.03  C          0.622304
         B          0.286954
         D          0.058916
         E          0.026302
         F          0.005523
30.1.04  B          0.487405
         C          0.416547
         F          0.060209
         D          0.022118
         A          0.009011
         E          0.004710
30.1.05  B          0.633705
         C          0.257311
         F          0.058069
         E          0.028824
         D          0.014096
         A          0.007995
30.1.06  C          0.285714
         F          0.261292
         E          0.193973
         B          0.145440
         D          0.113425
         A          0.000157
30.1.07  C          0.477783
         D          0.351394
         F          0.096577
         E          0.059510
         B          0.008615
         A          0.006121
30.3.08  E          0.434392
         F          0.375000
         D          0.107735
         C          0.082873
31.1.01  A          0.657585
         B          0.293025
         C          0.038818
         D          0.008100
         E          0.002472
31.3.02  A          0.538605
         C          0.223256
         B          0.187907
         E          0.021395
         D          0.016744
         F          0.012093
32.1.01  F          0.374033
         C          0.276531
         E          0.177127
         D          0.087739
         B          0.084570
Name: proportion, dtype: float64

In [31]:
df = gdf_manzanas.groupby('CVE_MET')['ICE_cat'].value_counts(normalize=True).reset_index(name='proportion')

In [34]:
df.sort_values(by=['CVE_MET','ICE_cat'])

     CVE_MET ICE_cat  proportion
0    01.1.01       A    0.860695
3    01.1.01       B    0.025886
1    01.1.01       C    0.042405
2    01.1.01       D    0.026567
5    01.1.01       E    0.019159
4    01.1.01       F    0.025290
11   02.1.01       A    0.045869
6    02.1.01       B    0.361841
7    02.1.01       C    0.218607
10   02.1.01       D    0.069591
9    02.1.01       E    0.103462
8    02.1.01       F    0.200629
14   02.2.02       C    0.009685
15   02.2.02       D    0.002690
13   02.2.02       E    0.030535
12   02.2.02       F    0.957089
18   02.2.03       B    0.115351
16   02.2.03       C    0.515580
19   02.2.03       D    0.096440
20   02.2.03       E    0.091662
17   02.2.03       F    0.180968
25   03.2.01       B    0.088128
22   03.2.01       C    0.288893
24   03.2.01       D    0.118025
23   03.2.01       E    0.206501
21   03.2.01       F    0.298453
30   03.2.02       B    0.008028
27   03.2.02       C    0.205410
29   03.2.02       D    0.075567
28   03.2.02       E    0.103490
26   03.2.02       F    0.607504
35   04.2.01       B    0.025992
31   04.2.01       C    0.297948
33   04.2.01       D    0.199179
32   04.2.01       E    0.289740
34   04.2.01       F    0.187141
41   05.1.01       A    0.053479
39   05.1.01       B    0.134434
36   05.1.01       C    0.383545
40   05.1.01       D    0.132199
37   05.1.01       E    0.148553
38   05.1.01       F    0.147791
46   05.1.02       B    0.005498
45   05.1.02       C    0.045357
44   05.1.02       D    0.054979
43   05.1.02       E    0.255040
42   05.1.02       F    0.639126
48   05.1.03       B    0.277179
47   05.1.03       C    0.290207
51   05.1.03       D    0.071204
50   05.1.03       E    0.149820
49   05.1.03       F    0.211590
57   05.1.04       A    0.045597
52   05.1.04       B    0.355506
53   05.1.04       C    0.304621
56   05.1.04       D    0.065676
55   05.1.04       E    0.104452
54   05.1.04       F    0.124147
62   05.3.05       B    0.002023
60   05.3.05       C    0.197977
61   05.3.05       D    0.101156
59   05.3.05       E    0.249422
58   05.3.05       F    0.449422
67   06.1.01       B    0.076989
63   06.1.01       C    0.324306
66   06.1.01       D    0.133367
64   06.1.01       E    0.249702
65   06.1.01       F    0.215636
72   06.3.02       B    0.070168
68   06.3.02       C    0.297087
71   06.3.02       D    0.150595
69   06.3.02       E    0.252359
70   06.3.02       F    0.229791
76   07.1.01       B    0.096913
74   07.1.01       C    0.240017
77   07.1.01       D    0.056983
75   07.1.01       E    0.157134
73   07.1.01       F    0.448953
83   07.1.02       A    0.002787
79   07.1.02       B    0.133945
80   07.1.02       C    0.098526
82   07.1.02       D    0.038835
81   07.1.02       E    0.078839
78   07.1.02       F    0.647069
88   08.1.01       A    0.046316
85   08.1.01       B    0.299297
86   08.1.01       C    0.197136
89   08.1.01       D    0.041578
87   08.1.01       E    0.078684
84   08.1.01       F    0.336989
92   08.1.02       C    0.065195
93   08.1.02       D    0.058961
91   08.1.02       E    0.226494
90   08.1.02       F    0.649351
99   08.2.03       A    0.042980
97   08.2.03       B    0.143920
95   08.2.03       C    0.164337
98   08.2.03       D    0.112484
96   08.2.03       E    0.147880
94   08.2.03       F    0.388399
101  08.3.04       C    0.292308
102  08.3.04       D    0.151874
100  08.3.04       E    0.418146
103  08.3.04       F    0.137673
104  09.1.01       A    0.568056
105  09.1.01       B    0.273538
106  09.1.01       C    0.089006
109  09.1.01       D    0.011956
108  09.1.01       E    0.015325
107  09.1.01       F    0.042119
114  10.2.01       B    0.029499
110  10.2.01       C    0.399017
113  10.2.01       D    0.134808
111  10.2.01       E    0.268240
112  10.2.01       F    0.168437
119  11.1.01       B    0.013440
118  11.1.01       C    0.075162
117  11.1.01       D    0.102912
116  11.1.01       E    0.358761
115  11.1.01       F    0.449726
125  11.1.02       A    0.007636
121  11.1.02       B    0.225545
120  11.1.02       C    0.366563
124  11.1.02       D    0.094404
123  11.1.02       E    0.144169
122  11.1.02       F    0.161683
130  11.2.03       B    0.006098
128  11.2.03       C    0.080703
129  11.2.03       D    0.076758
127  11.2.03       E    0.250359
126  11.2.03       F    0.586083
133  11.2.04       C    0.009940
134  11.2.04       D    0.000355
132  11.2.04       E    0.032481
131  11.2.04       F    0.957224
137  11.3.05       D    0.001653
136  11.3.05       E    0.006612
135  11.3.05       F    0.991736
140  11.3.06       C    0.047386
141  11.3.06       D    0.037037
139  11.3.06       E    0.182462
138  11.3.06       F    0.733115
142  12.1.01       B    0.355897
143  12.1.01       C    0.281228
146  12.1.01       D    0.048500
145  12.1.01       E    0.110084
144  12.1.01       F    0.204292
149  12.2.02       A    0.113208
147  12.2.02       B    0.460438
148  12.2.02       C    0.281376
152  12.2.02       D    0.024041
151  12.2.02       E    0.039197
150  12.2.02       F    0.081741
158  13.1.01       A    0.000178
154  13.1.01       B    0.219491
156  13.1.01       C    0.119109
157  13.1.01       D    0.079613
155  13.1.01       E    0.121328
153  13.1.01       F    0.460282
163  13.1.02       B    0.011724
161  13.1.02       C    0.277667
162  13.1.02       D    0.126394
160  13.1.02       E    0.286531
159  13.1.02       F    0.297684
167  13.3.03       C    0.028963
166  13.3.03       D    0.074695
165  13.3.03       E    0.361280
164  13.3.03       F    0.535061
168  14.1.01       A    0.574679
169  14.1.01       B    0.250335
170  14.1.01       C    0.104256
173  14.1.01       D    0.016953
172  14.1.01       E    0.019172
171  14.1.01       F    0.034605
179  14.1.02       A    0.003177
177  14.1.02       B    0.129225
174  14.1.02       C    0.359848
178  14.1.02       D    0.072427
175  14.1.02       E    0.273698
176  14.1.02       F    0.161626
184  14.3.03       B    0.025842
180  14.3.03       C    0.581910
183  14.3.03       D    0.120904
181  14.3.03       E    0.150438
182  14.3.03       F    0.120904
185  15.1.01       A    0.554492
186  15.1.01       B    0.369681
187  15.1.01       C    0.058292
189  15.1.01       D    0.005745
188  15.1.01       E    0.007661
190  15.1.01       F    0.004130
193  15.3.02       A    0.002591
191  15.3.02       B    0.959845
192  15.3.02       C    0.037565
194  15.3.03       A    0.999082
195  15.3.03       B    0.000918
198  16.1.01       C    0.017270
199  16.1.01       D    0.008003
197  16.1.01       E    0.058551
196  16.1.01       F    0.916175
205  16.1.02       A    0.002790
201  16.1.02       B    0.383377
200  16.1.02       C    0.398899
203  16.1.02       D    0.062084
204  16.1.02       E    0.026751
202  16.1.02       F    0.126100
210  16.1.03       B    0.000303
209  16.1.03       C    0.095209
208  16.1.03       D    0.106731
206  16.1.03       E    0.442996
207  16.1.03       F    0.354760
215  16.2.04       B    0.000650
214  16.2.04       C    0.081093
213  16.2.04       D    0.122940
212  16.2.04       E    0.323504
211  16.2.04       F    0.471813
219  16.3.05       C    0.023934
218  16.3.05       D    0.059722
217  16.3.05       E    0.207431
216  16.3.05       F    0.708913
224  16.3.06       B    0.000614
221  16.3.06       C    0.270885
222  16.3.06       D    0.209459
223  16.3.06       E    0.122850
220  16.3.06       F    0.396192
225  17.1.01       A    0.876323
226  17.1.01       B    0.051587
227  17.1.01       C    0.041887
228  17.1.01       D    0.014550
229  17.1.01       E    0.011684
230  17.1.01       F    0.003968
231  17.1.02       A    0.813626
232  17.1.02       B    0.156875
233  17.1.02       C    0.011365
236  17.1.02       D    0.004968
235  17.1.02       E    0.006086
234  17.1.02       F    0.007080
238  18.1.01       A    0.219591
237  18.1.01       B    0.546110
239  18.1.01       C    0.170907
241  18.1.01       D    0.017061
242  18.1.01       E    0.012061
240  18.1.01       F    0.034270
243  19.1.01       A    0.703227
244  19.1.01       B    0.107456
246  19.1.01       C    0.059911
248  19.1.01       D    0.021484
247  19.1.01       E    0.041227
245  19.1.01       F    0.066695
249  20.1.01       A    0.837270
250  20.1.01       B    0.099123
251  20.1.01       C    0.046520
252  20.1.01       D    0.010378
253  20.1.01       E    0.005815
254  20.1.01       F    0.000895
259  20.3.02       B    0.038087
255  20.3.02       C    0.431798
258  20.3.02       D    0.100531
257  20.3.02       E    0.156333
256  20.3.02       F    0.273251
264  20.3.03       B    0.004545
262  20.3.03       C    0.238889
261  20.3.03       D    0.253535
260  20.3.03       E    0.388889
263  20.3.03       F    0.114141
268  20.3.04       C    0.143602
267  20.3.04       D    0.227562
265  20.3.04       E    0.343370
266  20.3.04       F    0.285466
271  21.1.01       A    0.118739
270  21.1.01       B    0.260030
269  21.1.01       C    0.358174
273  21.1.01       D    0.102093
272  21.1.01       E    0.102720
274  21.1.01       F    0.058244
277  21.1.02       B    0.109964
275  21.1.02       C    0.463244
279  21.1.02       D    0.104800
276  21.1.02       E    0.214763
278  21.1.02       F    0.107230
282  21.1.03       B    0.213007
281  21.1.03       C    0.242460
284  21.1.03       D    0.079642
283  21.1.03       E    0.170123
280  21.1.03       F    0.294769
288  21.3.04       B    0.006908
285  21.3.04       C    0.648532
286  21.3.04       D    0.221071
287  21.3.04       E    0.122625
289  21.3.04       F    0.000864
293  21.3.05       B    0.020690
290  21.3.05       C    0.846305
291  21.3.05       D    0.108374
292  21.3.05       E    0.022660
294  21.3.05       F    0.001970
299  22.1.01       B    0.009558
296  22.1.01       C    0.314641
297  22.1.01       D    0.170718
298  22.1.01       E    0.141105
295  22.1.01       F    0.363978
303  23.1.01       A    0.095742
304  23.1.01       B    0.085978
300  23.1.01       C    0.457825
302  23.1.01       D    0.134617
301  23.1.01       E    0.144291
305  23.1.01       F    0.081548
308  23.2.02       C    0.026571
309  23.2.02       D    0.019694
307  23.2.02       E    0.280713
306  23.2.02       F    0.673023
314  23.2.03       B    0.002729
311  23.2.03       C    0.311681
313  23.2.03       D    0.091430
312  23.2.03       E    0.148745
310  23.2.03       F    0.445415
320  24.1.01       A    0.012801
316  24.1.01       B    0.313824
315  24.1.01       C    0.360871
319  24.1.01       D    0.069878
317  24.1.01       E    0.121346
318  24.1.01       F    0.121280
322  24.3.02       B    0.411396
321  24.3.02       C    0.501307
323  24.3.02       D    0.051228
324  24.3.02       E    0.035546
325  24.3.02       F    0.000523
330  24.3.03       B    0.003623
326  24.3.03       C    0.348551
329  24.3.03       D    0.106522
328  24.3.03       E    0.239130
327  24.3.03       F    0.302174
336  25.2.01       A    0.003017
333  25.2.01       B    0.152885
331  25.2.01       C    0.410159
334  25.2.01       D    0.140312
332  25.2.01       E    0.169840
335  25.2.01       F    0.123788
341  25.2.02       B    0.015716
339  25.2.02       C    0.093836
340  25.2.02       D    0.072170
338  25.2.02       E    0.283644
337  25.2.02       F    0.534635
346  25.2.03       B    0.018999
342  25.2.03       C    0.442052
343  25.2.03       D    0.260671
344  25.2.03       E    0.238125
345  25.2.03       F    0.040152
349  26.1.01       C    0.012061
350  26.1.01       D    0.003066
348  26.1.01       E    0.045380
347  26.1.01       F    0.939493
352  26.2.02       B    0.286900
351  26.2.02       C    0.479495
354  26.2.02       D    0.071891
355  26.2.02       E    0.056284
353  26.2.02       F    0.105429
356  26.2.03       A    0.571743
357  26.2.03       B    0.302589
359  26.2.03       C    0.033035
360  26.2.03       D    0.004872
361  26.2.03       E    0.003804
358  26.2.03       F    0.083956
362  26.2.04       C    0.378125
364  26.2.04       D    0.250000
363  26.2.04       E    0.280000
365  26.2.04       F    0.091875
369  26.3.05       C    0.043512
368  26.3.05       D    0.112665
367  26.3.05       E    0.223388
366  26.3.05       F    0.620435
373  27.1.01       A    0.140987
371  27.1.01       B    0.256267
370  27.1.01       C    0.285806
375  27.1.01       D    0.048539
374  27.1.01       E    0.121986
372  27.1.01       F    0.146415
381  28.1.01       A    0.001752
379  28.1.01       B    0.122033
376  28.1.01       C    0.262944
380  28.1.01       D    0.120599
377  28.1.01       E    0.247172
378  28.1.01       F    0.245499
387  28.1.02       A    0.000298
384  28.1.02       B    0.159699
382  28.1.02       C    0.385498
386  28.1.02       D    0.077502
385  28.1.02       E    0.141143
383  28.1.02       F    0.235860
393  28.2.03       A    0.004317
389  28.2.03       B    0.224141
388  28.2.03       C    0.614319
390  28.2.03       D    0.095881
391  28.2.03       E    0.052887
392  28.2.03       F    0.008455
398  28.2.04       A    0.033843
394  28.2.04       B    0.491350
395  28.2.04       C    0.300543
396  28.2.04       D    0.084985
397  28.2.04       E    0.063139
399  28.2.04       F    0.026140
402  28.2.05       B    0.170768
400  28.2.05       C    0.381655
403  28.2.05       D    0.144072
401  28.2.05       E    0.182699
404  28.2.05       F    0.120805
405  29.1.01       A    0.911028
406  29.1.01       B    0.072994
407  29.1.01       C    0.015979
408  29.3.02       A    0.856223
409  29.3.02       B    0.143777
414  30.1.01       B    0.031011
410  30.1.01       C    0.412902
412  30.1.01       D    0.194104
411  30.1.01       E    0.201953
413  30.1.01       F    0.160031
416  30.1.02       B    0.349739
415  30.1.02       C    0.378112
417  30.1.02       D    0.094094
418  30.1.02       E    0.093515
419  30.1.02       F    0.084540
421  30.1.03       B    0.286954
420  30.1.03       C    0.622304
422  30.1.03       D    0.058916
423  30.1.03       E    0.026302
424  30.1.03       F    0.005523
429  30.1.04       A    0.009011
425  30.1.04       B    0.487405
426  30.1.04       C    0.416547
428  30.1.04       D    0.022118
430  30.1.04       E    0.004710
427  30.1.04       F    0.060209
436  30.1.05       A    0.007995
431  30.1.05       B    0.633705
432  30.1.05       C    0.257311
435  30.1.05       D    0.014096
434  30.1.05       E    0.028824
433  30.1.05       F    0.058069
442  30.1.06       A    0.000157
440  30.1.06       B    0.145440
437  30.1.06       C    0.285714
441  30.1.06       D    0.113425
439  30.1.06       E    0.193973
438  30.1.06       F    0.261292
448  30.1.07       A    0.006121
447  30.1.07       B    0.008615
443  30.1.07       C    0.477783
444  30.1.07       D    0.351394
446  30.1.07       E    0.059510
445  30.1.07       F    0.096577
452  30.3.08       C    0.082873
451  30.3.08       D    0.107735
449  30.3.08       E    0.434392
450  30.3.08       F    0.375000
453  31.1.01       A    0.657585
454  31.1.01       B    0.293025
455  31.1.01       C    0.038818
456  31.1.01       D    0.008100
457  31.1.01       E    0.002472
458  31.3.02       A    0.538605
460  31.3.02       B    0.187907
459  31.3.02       C    0.223256
462  31.3.02       D    0.016744
461  31.3.02       E    0.021395
463  31.3.02       F    0.012093
468  32.1.01       B    0.084570
465  32.1.01       C    0.276531
467  32.1.01       D    0.087739
466  32.1.01       E    0.177127
464  32.1.01       F    0.374033

In [37]:
gdf_manzanas.groupby('CVE_MET')['ICE_norm'].mean().reset_index(name='%')

    CVE_MET         %
0   01.1.01  4.775755
1   02.1.01  1.404099
2   02.2.02  0.298224
3   02.2.03  1.068654
4   03.2.01  0.854589
5   03.2.02  0.562687
6   04.2.01  0.895645
7   05.1.01  1.227724
8   05.1.02  0.541388
9   05.1.03  1.180157
10  05.1.04  1.456723
11  05.3.05  0.678581
12  06.1.01  0.940534
13  06.3.02  0.915068
14  07.1.01  0.816590
15  07.1.02  0.725029
16  08.1.01  1.250418
17  08.1.02  0.498919
18  08.2.03  0.974942
19  08.3.04  0.844111
20  09.1.01  3.384450
21  10.2.01  0.915337
22  11.1.01  0.642114
23  11.1.02  1.157135
24  11.2.03  0.589172
25  11.2.04  0.287880
26  11.3.05  0.378679
27  11.3.06  0.479734
28  12.1.01  1.260638
29  12.2.02  1.847405
30  13.1.01  0.937668
31  13.1.02  0.810462
32  13.3.03  0.612907
33  14.1.01  2.943560
34  14.1.02  1.040814
35  14.3.03  1.045331
36  15.1.01  2.921947
37  15.3.02  2.181653
38  15.3.03  5.012020
39  16.1.01  0.362509
40  16.1.02  1.445581
41  16.1.03  0.684894
42  16.2.04  0.646990
43  16.3.05  0.493135
44  16.3.06  0.753283
45  17.1.01  5.841705
46  17.1.02  3.786552
47  18.1.01  2.199556
48  19.1.01  4.595684
49  20.1.01  4.935854
50  20.3.02  0.916684
51  20.3.03  0.856861
52  20.3.04  0.716192
53  21.1.01  1.873639
54  21.1.02  1.100763
55  21.1.03  1.012714
56  21.3.04  1.074802
57  21.3.05  1.194687
58  22.1.01  0.768862
59  23.1.01  1.334330
60  23.2.02  0.515444
61  23.2.03  0.741285
62  24.1.01  1.312496
63  24.3.02  1.513311
64  24.3.03  0.799423
65  25.2.01  1.132473
66  25.2.02  0.630764
67  25.2.03  0.992039
68  26.1.01  0.336699
69  26.2.02  1.336609
70  26.2.03  2.996689
71  26.2.04  0.907597
72  26.3.05  0.503117
73  27.1.01  1.562605
74  28.1.01  0.953397
75  28.1.02  1.065164
76  28.2.03  1.378853
77  28.2.04  1.693069
78  28.2.05  1.110798
79  29.1.01  8.769678
80  29.3.02  3.806970
81  30.1.01  0.941407
82  30.1.02  1.356775
83  30.1.03  1.406392
84  30.1.04  1.602091
85  30.1.05  1.752413
86  30.1.06  1.004455
87  30.1.07  0.998703
88  30.3.08  0.673409
89  31.1.01  3.266462
90  31.3.02  2.554090
91  32.1.01  0.854390

### Guardado paralelo

In [57]:
list(gdf_manzanas.columns.values)

['CVEGEO',
 'POPTOT2010',
 'POPTOT2020',
 'VIVTOT2010',
 'VIVTOT2020',
 'TVIVHAB2010',
 'TVIVHAB2020',
 'TVIVPAR2010',
 'TVIVPAR2020',
 'TVIVPARHAB2010',
 'TVIVPARHAB2020',
 'VIVPAR_HAB2010',
 'VIVPAR_HAB2020',
 'VIVPAR_UT2010',
 'VIVPAR_UT2020',
 'OCUPVIVPAR2010',
 'OCUPVIVPAR2020',
 'VIVPAR_DES2010',
 'VIVPAR_DES2020',
 'VIV1C2010',
 'VIV1C2020',
 'VIV2C2010',
 'VIV2C2020',
 'VIV3C2010',
 'VIV3C2020',
 'CVE_ENT',
 'CVE_MUN',
 'CVE_LOC',
 'CVE_AGEB',
 'CVE_MZA',
 'AMBITO',
 'TIPOMZA',
 'NOMGEO',
 'index_right',
 'CALIF_CLAS',
 'CVEMUN',
 'CVE_MET',
 'NOM_MET',
 'TIPO_MET',
 'TIPO_MUN',
 'area_ha',
 'DESHABITACION',
 'DIFPOP',
 'DIFVIV',
 'RELPOP',
 'RELVIV',
 'CVEPOP',
 'CVEVIV',
 'CVE',
 'TIPOLOGIA',
 'DENS_POP10',
 'DENS_POP20',
 'DENS_VIV10',
 'DENS_VIV20',
 'CUARTOS2010',
 'CUARTOS2020',
 'CPERC2010',
 'CPERC2020',
 'HABXVIV2010',
 'HABXVIV2020',
 'R_DESHAB',
 'SUBTIPOLOGÍA',
 'UE_10',
 'Emp_10',
 'UE_20',
 'Emp_20',
 'TAMAÑO',
 'TASA_EMP_MUN',
 'DIF_EMP',
 'DIF_UEC',
 'REL_EMP',
 'REL_UEC',
 'CVE_EMP',
 'CVE_UEC',
 'CVE_ue',
 'TIPOLOGIA_ue',
 'DENS_EMP20',
 'DENS_EMP10',
 'DENS_UEC20',
 'DENS_UEC10',
 'R_TAM',
 'SUBTIPOLOGÍA_ue',
 'num_edu',
 'num_sal',
 'num_rec',
 'num_ser',
 'IMP_EDU',
 'IMP_EDU_B',
 'IMP_EDU_C',
 'IMP_SAL',
 'IMP_SAL_B',
 'IMP_SAL_C',
 'IMP_REC',
 'IMP_REC_B',
 'IMP_REC_C',
 'IMP_SER',
 'IMP_SER_B',
 'IMP_SER_C',
 'FILTRADO',
 'CVE_EDU',
 'CVE_SAL',
 'CVE_REC',
 'CVE_SER',
 'CVE_EQ',
 'CVE_EDU_B',
 'CVE_SAL_B',
 'CVE_REC_B',
 'CVE_SER_B',
 'CVE_EQ_B',
 'CVE_EDU_C',
 'CVE_SAL_C',
 'CVE_REC_C',
 'CVE_SER_C',
 'CVE_EQ_C',
 'geometry',
 'count_S',
 'count_C',
 'count_D',
 'combo_signature',
 'CVE_EQ_C_v2',
 'IMP_EQ_nueva',
 'CVE_EQ_C_nueva']

In [58]:
manzanas_gpkg_path = r"D:\AFC\SSD\VOCES\DATA\Tratados\NAC\INT_MZN_NAC\Mzn_Tipologías_NAC_ImpEq_BufferB_rev.gpkg"
capa = 'Mzn_Subtipologias_UeEQ_filtrado_rev1'

#Guardar la capa resultante en un archivo .gpkg
gdf_manzanas.to_file(manzanas_gpkg_path, layer=capa, driver="GPKG")

# Arreglo metodología vieja

In [35]:
cols = ['CVE_EDU_C', 'CVE_SAL_C', 'CVE_REC_C', 'CVE_SER_C']

# Conteos por categoría
gdf_manzanas['count_S'] = (gdf_manzanas[cols] == 'S').sum(axis=1)
gdf_manzanas['count_C'] = (gdf_manzanas[cols] == 'C').sum(axis=1)
gdf_manzanas['count_D'] = (gdf_manzanas[cols] == 'D').sum(axis=1)

In [36]:
gdf_manzanas[['count_S','count_C','count_D']].sum(axis=1).value_counts()

4    938284
Name: count, dtype: int64

In [37]:
gdf_manzanas['combo_signature'] = (
    'S' + gdf_manzanas['count_S'].astype(str) + 
    '_C' + gdf_manzanas['count_C'].astype(str) + 
    '_D' + gdf_manzanas['count_D'].astype(str)
)

In [38]:
conteo_combinaciones = (
    gdf_manzanas['combo_signature']
    .value_counts()
    .reset_index()
)

conteo_combinaciones.columns = ['combinacion', 'frecuencia']
conteo_combinaciones

   combinacion  frecuencia
0     S3_C0_D1      281258
1     S2_C0_D2      184502
2     S2_C1_D1      121129
3     S3_C1_D0       96072
4     S1_C1_D2       73222
5     S1_C0_D3       49978
6     S4_C0_D0       30397
7     S0_C1_D3       28409
8     S1_C2_D1       22708
9     S0_C0_D4       18708
10    S0_C2_D2       13808
11    S2_C2_D0       13557
12    S0_C3_D1        2952
13    S1_C3_D0        1507
14    S0_C4_D0          77

In [39]:
tabla_revision = (
    gdf_manzanas.groupby(['CVE_EQ_C'])
      .size()
      .reset_index(name='n')
      .sort_values('CVE_EQ_C')
)
tabla_revision.loc['Total'] = tabla_revision.sum(numeric_only=True)
tabla_revision

      CVE_EQ_C         n
0            A   30397.0
1            B  109629.0
2            C    1584.0
3            D  428047.0
4            E  368627.0
Total      NaN  938284.0

In [40]:
tabla_revision = (
    gdf_manzanas.groupby(['combo_signature', 'CVE_EQ_C'])
      .size()
      .reset_index(name='n')
      .sort_values('combo_signature')
)
tabla_revision

   combo_signature CVE_EQ_C       n
0         S0_C0_D4        E   18708
1         S0_C1_D3        E   28409
2         S0_C2_D2        E   13808
3         S0_C3_D1        D    2952
4         S0_C4_D0        C      77
5         S1_C0_D3        E   49978
6         S1_C1_D2        E   73222
7         S1_C2_D1        D   22708
8         S1_C3_D0        C    1507
9         S2_C0_D2        E  184502
10        S2_C1_D1        D  121129
11        S2_C2_D0        B   13557
12        S3_C0_D1        D  281258
13        S3_C1_D0        B   96072
14        S4_C0_D0        A   30397

In [47]:
def asignar_clave(row):
    count_S = row['count_S']
    count_C = row['count_C']
    count_D = row['count_D']
    
    # 1️⃣ Superávit absoluto
    if count_S == 4:
        return 'A'
    
    # 2️⃣ Sin déficits (solo S y C)
    if count_D == 0:
        if (count_S == 3 and count_C == 1) or (count_S == 2 and count_C == 2):
            return 'B'
        elif count_C == 4 or (count_C == 3 and count_S == 1):
            return 'C'
    
    # 3️⃣ Déficit absoluto
    if count_D == 4:
        return 'F'
    
    # 4️⃣ Cobertura parcial (exactamente un D)
    if count_D == 1:
        return 'D'
    
    # 5️⃣ Deficiencia estructural (2 o 3 D)
    if count_D >= 2:
        return 'E'
    
    return np.nan

gdf_manzanas['CVE_EQ_C_v2'] = gdf_manzanas.apply(asignar_clave, axis=1)

In [48]:
tabla_revision = (
    gdf_manzanas.groupby(['combo_signature','CVE_EQ_C_v2'])
      .size()
      .reset_index(name='n')
      .sort_values('combo_signature')
)
tabla_revision.loc['Total'] = tabla_revision.sum(numeric_only=True)
tabla_revision

      combo_signature CVE_EQ_C_v2         n
0            S0_C0_D4           F   18708.0
1            S0_C1_D3           E   28409.0
2            S0_C2_D2           E   13808.0
3            S0_C3_D1           D    2952.0
4            S0_C4_D0           C      77.0
5            S1_C0_D3           E   49978.0
6            S1_C1_D2           E   73222.0
7            S1_C2_D1           D   22708.0
8            S1_C3_D0           C    1507.0
9            S2_C0_D2           E  184502.0
10           S2_C1_D1           D  121129.0
11           S2_C2_D0           B   13557.0
12           S3_C0_D1           D  281258.0
13           S3_C1_D0           B   96072.0
14           S4_C0_D0           A   30397.0
Total             NaN         NaN  938284.0

In [49]:
tabla_revision = (
    gdf_manzanas.groupby(['CVE_EQ_C_v2'])
      .size()
      .reset_index(name='n')
      .sort_values('CVE_EQ_C_v2')
)
tabla_revision.loc['Total'] = tabla_revision.sum(numeric_only=True)
tabla_revision

      CVE_EQ_C_v2         n
0               A   30397.0
1               B  109629.0
2               C    1584.0
3               D  428047.0
4               E  349919.0
5               F   18708.0
Total         NaN  938284.0

In [46]:
list(gdf_manzanas.columns.values)

['CVEGEO',
 'POPTOT2010',
 'POPTOT2020',
 'VIVTOT2010',
 'VIVTOT2020',
 'TVIVHAB2010',
 'TVIVHAB2020',
 'TVIVPAR2010',
 'TVIVPAR2020',
 'TVIVPARHAB2010',
 'TVIVPARHAB2020',
 'VIVPAR_HAB2010',
 'VIVPAR_HAB2020',
 'VIVPAR_UT2010',
 'VIVPAR_UT2020',
 'OCUPVIVPAR2010',
 'OCUPVIVPAR2020',
 'VIVPAR_DES2010',
 'VIVPAR_DES2020',
 'VIV1C2010',
 'VIV1C2020',
 'VIV2C2010',
 'VIV2C2020',
 'VIV3C2010',
 'VIV3C2020',
 'CVE_ENT',
 'CVE_MUN',
 'CVE_LOC',
 'CVE_AGEB',
 'CVE_MZA',
 'AMBITO',
 'TIPOMZA',
 'NOMGEO',
 'index_right',
 'CALIF_CLAS',
 'CVEMUN',
 'CVE_MET',
 'NOM_MET',
 'TIPO_MET',
 'TIPO_MUN',
 'area_ha',
 'DESHABITACION',
 'DIFPOP',
 'DIFVIV',
 'RELPOP',
 'RELVIV',
 'CVEPOP',
 'CVEVIV',
 'CVE',
 'TIPOLOGIA',
 'DENS_POP10',
 'DENS_POP20',
 'DENS_VIV10',
 'DENS_VIV20',
 'CUARTOS2010',
 'CUARTOS2020',
 'CPERC2010',
 'CPERC2020',
 'HABXVIV2010',
 'HABXVIV2020',
 'R_DESHAB',
 'SUBTIPOLOGÍA',
 'UE_10',
 'Emp_10',
 'UE_20',
 'Emp_20',
 'TAMAÑO',
 'TASA_EMP_MUN',
 'DIF_EMP',
 'DIF_UEC',
 'REL_EMP',
 'REL_UEC',
 'CVE_EMP',
 'CVE_UEC',
 'CVE_ue',
 'TIPOLOGIA_ue',
 'DENS_EMP20',
 'DENS_EMP10',
 'DENS_UEC20',
 'DENS_UEC10',
 'R_TAM',
 'SUBTIPOLOGÍA_ue',
 'num_edu',
 'num_sal',
 'num_rec',
 'num_ser',
 'IMP_EDU',
 'IMP_EDU_B',
 'IMP_EDU_C',
 'IMP_SAL',
 'IMP_SAL_B',
 'IMP_SAL_C',
 'IMP_REC',
 'IMP_REC_B',
 'IMP_REC_C',
 'IMP_SER',
 'IMP_SER_B',
 'IMP_SER_C',
 'FILTRADO',
 'CVE_EDU',
 'CVE_SAL',
 'CVE_REC',
 'CVE_SER',
 'CVE_EQ',
 'CVE_EDU_B',
 'CVE_SAL_B',
 'CVE_REC_B',
 'CVE_SER_B',
 'CVE_EQ_B',
 'CVE_EDU_C',
 'CVE_SAL_C',
 'CVE_REC_C',
 'CVE_SER_C',
 'CVE_EQ_C',
 'geometry',
 'count_S',
 'count_C',
 'count_D',
 'combo_signature']

In [ ]:
manzanas_gpkg_path = r"D:\AFC\SSD\VOCES\DATA\Tratados\NAC\INT_MZN_NAC\Mzn_Tipologías_NAC_ImpEq_BufferB_rev.gpkg"
capa = 'Mzn_Subtipologias_UeEQ_filtrado_rev1'

#Guardar la capa resultante en un archivo .gpkg
gdf_manzanas.to_file(manzanas_gpkg_path, layer=capa, driver="GPKG")